# Generated by Django 3.2.4 on 2021-06-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('latest_price', models.FloatField(blank=True)),
                ('latest_day_change', models.FloatField(blank=True)),
                ('last_updated', models.DateTimeField(blank=True)),
            ],
        ),
    ]
