# Generated by Django 3.2.4 on 2021-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scrape_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='last_updated',
            field=models.FloatField(blank=True),
        ),
    ]
