# Generated by Django 3.2.4 on 2021-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scrape_api', '0002_alter_symbol_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('latest_price', models.FloatField(blank=True, null=True)),
                ('latest_day_change', models.FloatField(blank=True, null=True)),
                ('last_updated', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
