version: '3'

services:
  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: '*'
        DJANGO_CORS_ORIGIN_WHITELIST: '*'
    command: python manage.py runserver
    ports:
      - "8000:8000"
